id: gerador_prompt
name: "Gerador Inteligente de Prompts"
version: "1.0.0"
description: >
  Combina persona, intenção e diretrizes de formato para gerar prompts otimizados e coerentes.
  Implementa um ciclo de feedback para validação automática e ajuste contextual.

atoms:
  - id: extract_intent
    path: atoms/logic/extract_intent.py
    function: extract_intent
  - id: merge_persona_context
    path: atoms/logic/merge_persona_context.py
    function: merge_persona_context
  - id: compose_prompt
    path: atoms/logic/compose_prompt.py
    function: compose_prompt
  - id: validate_prompt
    path: atoms/logic/validate_prompt.py
    function: validate_prompt

data_units:
  - path: atoms/data_units/persona_expert.yaml
  - path: atoms/data_units/format_guidelines.yaml

prompt_units:
  - path: atoms/prompt_units/meta_reasoning.yaml
  - path: atoms/prompt_units/validation_feedback.yaml

flow:
  - step: extract_intent
    input: { user_input: "string" }
    output: intent
  - step: merge_persona_context
    input: { intent: "from.extract_intent", persona: "persona_expert.yaml" }
    output: context_block
  - step: compose_prompt
    input: { context: "from.merge_persona_context", format_rules: "format_guidelines.yaml" }
    output: draft_prompt
  - step: validate_prompt
    input: { prompt: "from.compose_prompt", criteria: "validation_feedback.yaml" }
    output: final_prompt
